"""initial models

Revision ID: 001
Revises:
Create Date: 2026-01-29 18:51:25.319341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create TimescaleDB extension
    op.execute('CREATE EXTENSION IF NOT EXISTS timescaledb')

    op.create_table('asset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_asset_market_cap_rank'), 'asset', ['market_cap_rank'], unique=False)
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=True)
    op.create_table('quote',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_quote_name'), 'quote', ['name'], unique=True)
    op.create_table('section',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('special_fields', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    op.create_table('contract',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('funding_interval', sa.Integer(), nullable=False),
    sa.Column('quote_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('special_fields', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('deprecated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['asset_name'], ['asset.name'], ),
    sa.ForeignKeyConstraint(['section_name'], ['section.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_name', 'section_name', 'quote_name')
    )
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=True)
    op.create_index(op.f('ix_contract_quote_name'), 'contract', ['quote_name'], unique=False)
    op.create_table('historical_funding_point',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'timestamp'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )
    op.create_table('live_funding_point',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'timestamp'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )

    # Configure hypertable chunk intervals manually
    # live_funding_point: 1 hour chunks (high-frequency data)
    with op.get_context().autocommit_block():
        op.execute(
            "SELECT create_hypertable('live_funding_point', 'timestamp', "
            "chunk_time_interval => INTERVAL '1 hour', if_not_exists => TRUE)"
        )

    # historical_funding_point: 1 day chunks (historical data)
    with op.get_context().autocommit_block():
        op.execute(
            "SELECT create_hypertable('historical_funding_point', 'timestamp', "
            "chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_funding_point')
    op.drop_table('historical_funding_point')
    op.drop_index(op.f('ix_contract_quote_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_quote_name'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_index(op.f('ix_asset_market_cap_rank'), table_name='asset')
    op.drop_table('asset')

    # Drop TimescaleDB extension
    op.execute('DROP EXTENSION IF EXISTS timescaledb')
    # ### end Alembic commands ###
